# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongodb-plantitas-1.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123qwe
      MONGO_INITDB_DATABASE: plantitas
    ports:
      - 27017:27017

  mongo-express: 
    image: mongo-express
    restart: always
    container_name: mongodb-ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123qwe